# Generated by Django 2.1.7 on 2019-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(max_length=66)),
                ('tag2', models.CharField(max_length=66)),
            ],
        ),
    ]
